# Project: 华为机试
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
RES      = 华为机试_private.res
OBJ      = 华为机试/main.o $(RES)
LINKOBJ  = 华为机试/main.o $(RES)
LIBS     = -L"E:/C++/devc++/Dev-Cpp/MinGW64/lib" -L"E:/C++/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"E:/C++/devc++/Dev-Cpp/MinGW64/include" -I"E:/C++/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/C++/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/C++/devc++/Dev-Cpp/MinGW64/include" -I"E:/C++/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/C++/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/C++/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 华为机试.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

华为机试/main.o: 华为机试/main.cpp
	$(CPP) -c 华为机试/main.cpp -o 华为机试/main.o $(CXXFLAGS)

华为机试_private.res: 华为机试_private.rc 
	$(WINDRES) -i 华为机试_private.rc --input-format=rc -o 华为机试_private.res -O coff 

